USE Sample;

DELETE FROM tblGender WHERE ID = 2;

ALTER TABLE tblPerson
	DROP CONSTRAINT tblPerson_GenderID_FK;

ALTER TABLE tblPerson
	ADD CONSTRAINT tblPerson_GenderID_FK 
	FOREIGN KEY (GenderID)
	REFERENCES tblGender(ID)
    ON DELETE SET DEFAULT;

DELETE FROM tblGender WHERE ID = 2;

ALTER TABLE tblPerson
	DROP CONSTRAINT tblPerson_GenderID_FK;

ALTER TABLE tblPerson
	ADD CONSTRAINT tblPerson_GenderID_FK 
	FOREIGN KEY (GenderID)
	REFERENCES tblGender(ID)
    ON DELETE SET NULL;

DELETE FROM tblGender WHERE ID = 1;

ALTER TABLE tblPerson
	DROP CONSTRAINT tblPerson_GenderID_FK;

ALTER TABLE tblPerson
	ADD CONSTRAINT tblPerson_GenderID_FK 
	FOREIGN KEY (GenderID)
	REFERENCES tblGender(ID)
    ON DELETE CASCADE;

DELETE FROM tblGender WHERE ID = 3;